# Generated by Django 3.1.4 on 2020-12-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_fname', models.CharField(max_length=100)),
                ('customer_lname', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_mobile', models.IntegerField(max_length=10)),
                ('customer_password', models.CharField(max_length=50)),
            ],
        ),
    ]
