# Generated by Django 3.1.4 on 2020-12-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_mobile',
            field=models.IntegerField(),
        ),
    ]
