# Generated by Django 3.1.4 on 2021-01-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201230_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(db_column='BID', primary_key=True, serialize=False)),
                ('customer', models.IntegerField()),
                ('category', models.IntegerField()),
                ('sub_category', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('order_date', models.IntegerField()),
                ('ship_date', models.IntegerField()),
                ('payment_status', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=0, upload_to='store/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='addesss',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='pin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='shiping_addesss',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='shiping_city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='shiping_pin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
