# Generated by Django 3.1.4 on 2021-01-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210102_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_cat_id',
            field=models.AutoField(db_column='BID', default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(db_column='BID', default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.AutoField(db_column='BID', default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
