# Generated by Django 3.1.4 on 2021-01-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210102_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('sub_cat_id', models.AutoField(db_column='BID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('disc', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='store/images')),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='sub_cat_id',
            new_name='cat_id',
        ),
    ]
