# Generated by Django 3.1.4 on 2021-01-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210102_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
