# Generated by Django 3.1.4 on 2021-01-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210103_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='colour',
        ),
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.ManyToManyField(to='store.Colour'),
        ),
    ]
